<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'O nama',
    'Activities' => 'Aktivnosti',
    'Body' => '',
    'Check your email for further instructions.' => 'Provjerite email za dodatne upute',
    'Contact' => 'Kontakt',
    'Documents' => 'Dokumenti',
    'Email' => 'Email',
    'Gallery' => 'Galerija',
    'History' => 'Povijest',
    'Home' => 'Početna',
    'It is worth mentioning that the Club of Sport Fishing on Sea Gaun greatly assists with the development of the island 
                    and the life of the islanders. For example, Gaun sponsored the local board of the Island Kaprije and with mutual funds 
                    helped to build promenade, new avenue. Donation will also be given to rebuild an old olive oil mill. SKRM Gaun from its 
                    own funding has repaired a smaller pier where today moorings are charged. SKRM Gaun sponsors children’s sports games where 
                    children compete in a sack race, play football on the playground, run with an egg in a spoon.' => 
                    'Vrijedno je spomenuti da Sportski Klub za Ribolov na Moru Gaun uvelike potpomaže razvoju otoka i životu otočana, pa tako Gaun 
                    sponzorira mjesni odbor Kaprije te se zajedničkim sredstvima izgradila šetnica, novi drvored, dala se i donacija za uređenje uljare.
                     ŠKRM Gaun je sam iz svojih financijskih sredstava sanirao malu rivu na kojoj i danas naplaćuje privez. SKRM Gaun sponzorira Dječje 
                     Sportske Igre gdje se djeca takmiče u trčanju u vrećama, igra se mali nogomet na igralištu, trči se i sa jajetom u žlici.',
    'Login' => 'Prijava',
    'Logout (i' => 'Odjava',
    'Members' => 'Članovi',
    'Name' => 'Ime',
    'New password saved.' => 'Nova lozinka spremljena',
    'News' => 'Vijesti',
    'Services' => 'Usluge',
    'Servis Information' => 'Servisne informacije',
    'Signup' => 'Registracija',
    'Sorry, we are unable to reset password for the provided email address.' => 'Lozinku nije moguće resetirati. Pogrešan Email',
    'Subject' => 'Subjekt',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Hvala što ste nas kontakitrali. Javit ćemo se u najkraćem mogućem roku.',
    'The requested page does not exist.' => 'Stranica ne postoji',
    'There was an error sending your message.' => 'Dogodila se pogreška prilikom slanja Vašeg email -a',
    'This is the About page. You may modify the following file to customize its content:' => '',
    'Verification Code' => 'Verifikacijski kod',
    'error' => 'pogreška',
    'success' => 'uspijeh',
];
