<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Sigurni želite izbrisati ovu stavku?',
    'Create Document' => 'Napravi Dokument',
    'Create Image' => 'Napravi Sliku',
    'Create Member' => 'Napravi Člana',
    'Create Member Contact' => 'Napravi Kontakt Člana',
    'Create News' => 'Napravi Vijesti',
    'Create Services' => 'Napravi Uslugu',
    'Create Video' => 'Napravi Video',
    'Create Video Property' => 'Napravi Svojstvo Videa',
    'Delete' => 'Izbriši',
    'Documents' => 'Dokumenti',
    'Images' => 'Slike',
    'Member Contacts' => 'Kontakti članova',
    'Members' => 'Članovi',
    'News' => 'Vijesti',
    'Reset' => '',
    'Save' => 'Spremi',
    'Search' => 'Traži',
    'Services' => 'Usluge',
    'The requested page does not exist.' => 'Zahtijevana stranica ne postiji',
    'Update' => 'Ažururaj',
    'Update Document: {nameAttribute}' => 'Ažuriraj dokument: {nameAttribute}',
    'Update Image: {nameAttribute}' => 'Ažuriraj sliku: {nameAttribute}',
    'Update Member Contact: {nameAttribute}' => 'Ažuriraj kontakt člana: {nameAttribute}',
    'Update Member: ' => 'Ažuriraj člana',
    'Update News: {nameAttribute}' => 'Ažuriraj vijesti {nameAttribute}',
    'Update Services: ' => 'Ažuriraj Usluge:',
    'Update User: ' => 'Ažuriraj korisnika',
    'Update Video Property: {nameAttribute}' => 'Ažuriraj svojstvo videa: {nameAttribute}',
    'Update Video: ' => 'Ažuriraj video: ',
    'Users' => 'Korisnici',
    'Video Properties' => 'Svojstva videa',
    'Videos' => 'Video',
    'delete' => 'izbriši',
    'update' => 'ažuriraj',
];
